package bdbeans;
// Generated 27 janv. 2024, 23:06:48 by Hibernate Tools 5.6.7.Final

/**
 * Personnes generated by hbm2java
 */
public class Personnes implements java.io.Serializable {

	private int idpersonne;
	private String prenom;
	private String nom;
	private String email;
	private String password;

	public Personnes() {
	}

	public Personnes(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	public Personnes(int idpersonne, String prenom, String nom, String email, String password) {
		this.idpersonne = idpersonne;
		this.prenom = prenom;
		this.nom = nom;
		this.email = email;
		this.password = password;
	}

	public int getIdpersonne() {
		return this.idpersonne;
	}

	public void setIdpersonne(int idpersonne) {
		this.idpersonne = idpersonne;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
