package bdbeans;
// Generated 27 janv. 2024, 23:06:48 by Hibernate Tools 5.6.7.Final

/**
 * Personnes generated by hbm2java
 */
public class Produit implements java.io.Serializable {

	private int idProduit;
	private String numero;
	private String libelle;
	private double prix;
	public int getIdProduit() {
		return idProduit;
	}
	public String getNumero() {
		return numero;
	}
	public String getLibelle() {
		return libelle;
	}
	public double getPrix() {
		return prix;
	}
	public void setIdProduit(int idProduit) {
		this.idProduit = idProduit;
	}
	public void setNumero(String numero) {
		this.numero = numero;
	}
	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}
	public Produit() {
		
	}
	public Produit(int idProduit, String numero, String libelle, double prix) {
		
		this.idProduit = idProduit;
		this.numero = numero;
		this.libelle = libelle;
		this.prix = prix;
	}
	public void setPrix(double prix) {
		this.prix = prix;
	}

	
	

}
